name: "Create File Action (on Any Platform)"
description: "Github Action to create a new file from environment config (on any platform)"
author: "Barton Ip"
branding:
  icon: "maximize"
  color: "purple"
inputs:
  filename:
    description: "Full filepath of the file you'd like to create. (e.g. /tmp/log.txt or C:\\log.txt)"
    required: true
  data:
    description: "The contents of the file. Default value is empty string."
    required: false
    default: ""
  isBase64:
    description: "Boolean flag to mark if file data is base64 or not. Valid values are \"true\" and \"false\". Default value is \"false\""
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
   - name: "Decoding/Creating base64 file"
     run: echo ${{ inputs.data }} | base64 --decode > ${{ inputs.filename }}
     shell: bash
     if: ${{ inputs.isBase64 == 'true '}}
   - name: "Creating File"
     run: echo ${{ inputs.data }} > ${{ inputs.filename }}
     shell: bash
     if: ${{ inputs.isBase64 == 'false '}}
      